# --- [1] 开关 ---
enable-hy=false
enable-tu=true
enable-vl=false
enable-ct=false

# --- [2] 基础 ---
domain=51.161.208.84
remarks-prefix=ouipanel
force-exec-permission=true

# --- [3] VL 模块 ---m-core-c
vl-port=4932
vl-uuid=81a21d36-a6db-44e6-b5b9-6621f3928577
vl-dest=www.bing.com
vl-sni=www.bing.com
vl-pri-key=uE6hK6eS7P8uN_X4A2M-V5bC8dE9fG0hI1jK2lM3nO4

# --- [4] TU 模块 --- m-core-b
tu-port=4892
tu-uuid=b16fad96-dd9c-4bfd-89b7-f88b894a56a3
tu-pass=7035591f

# --- [5] HY 模块 ---m-core-a
hy-port=33984
hy-pass=magic_pass_123

# --- [6] CT 模块 ---m-core-d
ct-token= ""
ct-local-url=http://localhost:7903
ct-vl-uuid=68ac8f3b-5574-4bf4-b031-a82f064b9294
ct-domain= ""